### ISSUE TITLE
Monitor name got mixed up with version 6

### ISSUE THREAD

**Issue by esercankutay** [themightydeity/gnome-display-brightness-ddcutil#13]
with version 6 on gnome 3.36 with ubuntu 20.04 monitor names got mixed up. To be specific when i change the brightness level of first monitor second monitor changes. other monitors' brightness level bar is'nt functional. i reverted it back to version 4 and all is fine.

**Comment by themightydeity** [comment]
Could you try version 7 and report back if it works for you?

**Comment by esercankutay** [comment]
thanks for the response. i'm on version 7 right now and problem seems to be solved for hdmi+vga setup.
