### ISSUE TITLE
Extension conflict

### ISSUE THREAD

**Issue by Roosted7** [themightydeity/gnome-display-brightness-ddcutil#2]
Hi! Thanks for making this extension, it seems very handy - unfortunately I can't get it to work under GNOME 3.36 (Arch Linux)

The extension fails to install / load with the following error:
```
JS ERROR: Extension display-brightness-ddcutil@themightydeity.github.com: Error: Extension point conflict: there is already a status indicator for role BrightnessSlider
                                           addToStatusArea@resource:///org/gnome/shell/ui/panel.js:1108:19
                                           SliderPanelMenu@/home/thomas/.local/share/gnome-shell/extensions/display-brightness-ddcutil@themightydeity.github.com/extension.js:169:20
                                           enable@/home/thomas/.local/share/gnome-shell/extensions/display-brightness-ddcutil@themightydeity.github.com/extension.js:51:9
                                           _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:160:32
                                           loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:311:26
                                           callback@resource:///org/gnome/shell/ui/extensionDownloader.js:204:39
                                           gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:97:13
```

The brightness icon does appear, but there is no interaction possible. The icon only goes away after a shell restart. GNOME also reports an 'error with the extension'

Is it clear from the above error what could be wrong? Can I provide more information?
Thanks for looking into this :)

**Comment by themightydeity** [comment]
I changed the name BrightnessSlider to DDCUtilBrightnessSlider in  #4 . I hope that will fix the probelm for you. 
I guess you got the error because you are using some other extensions which is using that name.

**Comment by Roosted7** [comment]
Awesome! That indeed fixes it :tada:

It wouldn't expect another extension to use that name.. I'm using the following other extensions:
 - Caffeine
 - Dash to Dock
 - Launch new instance
 - No screen blank
 - No topleft hot corner
 - Quick close in overview
