### ISSUE TITLE
Use of async command causes many calls if dragging slider

### ISSUE THREAD

**Issue by flukejones** [themightydeity/gnome-display-brightness-ddcutil#3]
Great extension, it's something I was looking at writing myself.

I noticed that if I drag the slider it causes many calls to ddcutil, which in turn can cause something a bit like seemingly random up/down of brightness while dragging. I looked briefly at how gnome-shell handles it for default displays (like laptops) it uses what could be best described as a notifier system.

Something like:
1. slider changes value,
2. on drag finish, commit the value to dconf
3. a dconf calls a callback on this and updates physical display.

Sorry about the not so detailed description.

**Comment by themightydeity** [comment]
I added some timer to work around it, which has bind with delay type of efffect #4 .

Storing and reading from dconf might be good idea. I will look into it, if it is possible without writing a wrapper for ddcutil and this extension itself can register the callback.

**Comment by themightydeity** [comment]
The workaround seems to be good enough, so I am closing this issue.
