### ISSUE TITLE
Add support for software-only brightness control

### ISSUE THREAD

**Issue by nathanmiddleton** [themightydeity/gnome-display-brightness-ddcutil#7]
I have a mix of monitors that support ddci and some that support nothing. It would be nice to have a single place to support brightness on all monitors.

Maybe there could be an option to support ddci failed monitors with xrandr software brightness?

**Comment by themightydeity** [comment]
I do not think I would be adding that feature at the moment but if I get more requests and someone is willing contribute to this project, I am happy to review some pull requests. 
This project's whole basis is ddcutil as it is in the name.
