### ISSUE TITLE
Not working with devices that do work with ddcutil

### ISSUE THREAD

**Issue by mustdobetter** [themightydeity/gnome-display-brightness-ddcutil#8]
I am able to control my two monitors via ddcutil (without sudo), however when running this extension it shows the error: 

> ddcutil didn't find any display with DDC/CI support

This is the output of `ddcutil detect`:

```
Display 1
   I2C bus:             /dev/i2c-5
   EDID synopsis:
      Mfg id:           GSM
      Model:            LG UltraFine
      Serial number:    �������������
      Model year      : 2245
      EDID version:     1.4
   VCP version:         Detection failed

Display 2
   I2C bus:             /dev/i2c-6
   EDID synopsis:
      Mfg id:           GSM
      Model:            LG UltraFine
      Serial number:    612NTCZ0G851
      Manufacture year: 2016
      EDID version:     1.4
   VCP version:         Detection failed
```

As I say, I'm able to control the brightness on the command line e.g:

`ddcutil --display 2 setvcp 10 100`

**Comment by themightydeity** [comment]
@mustdobetter 

This is roughly what the extension checks to detect displays, could you try to run this once and let me know what happens?
```
ddcutil detect --brief | grep "/dev/i2c" | awk -F'/dev/i2c-' '{printf($2 "=>"); system("ddcutil getvcp --nodetect --brief 10 --bus " $2) }'
```

**Comment by mustdobetter** [comment]
@themightydeity 

Apologies for the belated reply. Here is the output you requested from the above command:

```
5=>VCP 10 C 50 100
6=>VCP 10 C 56 100
```

**Comment by themightydeity** [comment]
@mustdobetter  could you update to latest version (7) of the extesion, let me know if it fixes the issue for you.

**Comment by mustdobetter** [comment]
Where can I do that? There don't seem to be any releases in this Github project, and on the Gnome extension page (https://extensions.gnome.org/extension/2645/brightness-control-using-ddcutil/) all I seem to be able to do is install/uninstall. The only versions mentioned are the Shell Version (3.34, 3.36). Thanks.

**Comment by mustdobetter** [comment]
I've just twigged - I select the shell version first. Sorry - will feed back shortly.

**Comment by mustdobetter** [comment]
@themightydeity after upgrading to version 7 manually I just get the "Initializing" message and nothing more.

**Comment by themightydeity** [comment]
@mustdobetter which gnome version are you using? This extension is working properly in 3.36.

**Comment by pelletier** [comment]
I'm hitting a similar issue here.

From my shell:

```
/usr/bin/ddcutil detect --brief
Display 1
   I2C bus:             /dev/i2c-10
   Monitor:             DEL:DELL P2715Q:54KKD71C768L
```

But this extension only show "Initializing" when I click on it.

Adding some logs in the code ([here](https://github.com/themightydeity/gnome-display-brightness-ddcutil/blob/master/display-brightness-ddcutil%40themightydeity.github.com/extension.js#L246)), it seems like when it calls `/usr/bin/ddcutil detect --brief`, the callback receives this as `stdout`:

```
No displays found

```

No idea why it would get a different output than the shell.

* Gnome 3.36.3 (Ubuntu Focal)
* Version 7 of the ext.
