### ISSUE TITLE
Extension only shows "Initializing"

### ISSUE THREAD

**Issue by hmmSalat** [themightydeity/gnome-display-brightness-ddcutil#9]
Hey,

first oft all: this is a great extension!

But it no longer works for me since the latest update. I always get this message:
![ddcutil-initializing](https://user-images.githubusercontent.com/48926955/85925364-4297b600-b898-11ea-98b3-3b72c39dfa0d.png)

Is this a problem with the extension? Or ist it my dducitl installation? I noticed, that my ddcutil installation seems to have some issues, too. I can adjust the screen brightness using e.g. ddcutil setvcp 10 100. But i always get the following error message:
```
[hmmsalat@arch-desktop ~]$ ddcutil setvcp 10 100
Open failed for /dev/usb/hiddev2: errno=EACCES(13): Permission denied
```

Can somebody help me?

extension-version: 6
gnome version: 3.36.3-1
kernel: 5.7.6.arch1-1
ddcutil version: 0.9.9-1

**Comment by hmmSalat** [comment]
Changed permissions for /dev/usb/hiddev2. Error message is gone. Extension works now.

**Comment by 1player** [comment]
Same here, I managed to fix it by running `ddcutil --brief detect > ~/.cache/ddcutil_detect` and restarting the extension.

**Comment by themightydeity** [comment]
@1player That is a the workaround I have added, I suppose you checked Issue section in the readme file. Remeber to recreate that file if you change monitor configuration,  like added new monitors or changed connection ports in GPU or motherboard etc.

**Comment by themightydeity** [comment]
@hmmSalat I am closing this issue, it seems like the issue for you was that when the error message was shown it broke the extension's output parser.

**Comment by 1player** [comment]
It still is a bug with the cached file, because I often move between one and two monitors, and the cached file requires me to restart the extension manually every time I attach or detach the monitor.

The parser should just ignore the error altogether, considering it's printed on stderr, and the important stuff it's interested in is coming from stdout.

**Comment by themightydeity** [comment]
@1player parser is not using stderr at all, were you also getting similar permission errors like this?
```
Open failed for /dev/usb/hiddev2: errno=EACCES(13): Permission denied
```

As for hotloading monitor a relaod button or something else is in pipeline, I will add that when I have a bit of free time.

**Comment by themightydeity** [comment]
In the meantime if both @1player  and @hmmSalat could send me output of following command
```
ddcutil detect --brief | grep "/dev/i2c" | awk -F'/dev/i2c-' '{printf($2 "=>"); system("ddcutil getvcp --brief 10 --bus " $2) }'
```

This is roughly what this extension does to detect monitor.

**Comment by hmmSalat** [comment]
@themightydeity 
```
[hmmsalat@arch-desktop ~]$ ddcutil detect --brief | grep "/dev/i2c" | awk -F'/dev/i2c-' '{printf($2 "=>"); system("ddcutil getvcp --brief 10 --bus " $2) }'
Open failed for /dev/usb/hiddev2: errno=EACCES(13): Permission denied
9=>VCP 10 C 100 100
```

**Comment by hmmSalat** [comment]
Fixed in version 7. Thank you! :-) :+1:

**Comment by pimvanderheijden** [comment]
Installed from extensions.gnome.org but stuck on "Initializing", what can I do?
I'm on Ubuntu 20.04.3

**Comment by daitj** [comment]
@pimvanderheijden

Have you checked the readme of this project?

You need to make sure that you can run and detect monitors with `ddcutil detect` shell command (without sudo or root).

**Comment by pimvanderheijden** [comment]
The name of the section **Automatically from GNOME extensions** suggests no additional setup is needed. Moreover, I don't have the ddcutil command available after installing. Does this mean I should install from source?

**Comment by daitj** [comment]
You need to install it from your package manager,

  `sudo apt install ddcutil` 

then follow the rest of the steps from here:
https://github.com/daitj/gnome-display-brightness-ddcutil#setup-ddcutil

**Comment by pimvanderheijden** [comment]
Great, that works fabulously. Thanks!
